CA-289145: close socket if error occurs when using lwt connect
xapi-project/xapi-xe pull request #15
Opened 2018-05-21 09:32 UTC by krizex

Signed-off-by: Yang Qian <yang.qian@citrix.com>

2018-05-21 09:59 UTC, mseri requested changes
In all those I think you need to use `Lwt.fail` for the exceptions,  `Lwt.catch` instead of `try...with` and bind the close: `(fun e -> Lwt_unix.close sock >>= fun () -> Lwt.fail e)`. Or something like that

2018-05-22 05:21 UTC, krizex commented
Thanks @mseri , updated.

2018-05-22 08:06 UTC, mseri commented on src/newcli.ml
>      try_lwt
This is the old camlp4 syntax... this makes me wonder if this package is maintained at all. Does it even compile in the new xs-opam?

2018-05-22 08:07 UTC, mseri commented
Sorry for not spotting this earlier, this repository needs to be deprecated and archived as it is no longer maintained and the new xe is shipped and buildable from the main xen-api repository

2018-05-22 08:07 UTC, closed without merging

2018-05-22 08:07 UTC, mseri commented
@robhoes or @jonludlam can you archive this?

2018-05-22 08:11 UTC, mseri commented on src/newcli.ml
> +      Lwt_unix.close sock >>= Lwt.fail e
`>>=` should be `>>= fun () ->`

2018-05-22 08:11 UTC, mseri commented on src/newcli.ml
> +        Lwt_unix.close sock >>= Lwt.fail e
`>>=` should be `>>= fun () ->`